export const strings={
    signIn:"SIGN IN",
    signUp:"SIGN UP",
    firstName:"First Name",
    lastName:"Last Name",
    email:"Email",
    password:"password",
    confirmPassword:"Confirm Password",
    mobileNumber:"mobileNumber",
    donthaveanaccount:"Don't have an account?",
    allReadyHave:"Aleady have an account?",
    logIn:"LOGIN",
    home:"Home",
    adduser:"Adduser",
    profile:"Profile",
    id:"Id",
    fName:"FName",
    lName:"LName",
    add:"ADD",
    cancel:"CANCEL",
    camera:"camera",
    gallery:"gallery",
    colon:":",
    large:"large",
    edit:"Edit",
    done:"Done",
    regester:"Regester",
    Contactno:"Contact no",
    height:"height",
    padding:"padding",
    logout:"Logout",
    searchdata:"searchdata",
    nodatafound:"no data found"
}
