export const strings={
    signIn:"SIGN IN",
    signUp:"SIGN UP",
    firstName:"First Name",
    lastName:"Last Name",
    email:"Email",
    password:"password",
    confirmPassword:"Confirm Password",
    mobileNumber:"mobileNumber",
    donthaveanaccount:"Don't have an account?",
    allReadyHave:"Aleady have an account?",
    logIn:"LOGIN",
    home:"Home",
    adduser:"Adduser",
    profile:"Profile",
    id:"Id",
    fName:"FName",
    lName:"LName",
    padding:"padding",
    large:"large",
    add:"ADD",
    cancel:"CANCEL",
    camera:"camera",
    gallery:"gallery",
    
}